//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by _WispWin.rc
//
#define MNU_Full                        101
#define DlgSelectServer                 114
#define DlgSelectDir                    115
#define DlgOpenFile                     117
#define dlgSelectSingleDir              120
#define WISPSheet                       131
#define COBOLSheet                      132
#define WISPOutput                      133
#define COBOLOutput                     134
#define IDI_ICON1                       134
#define MainIcon                        134
#define lb_DirList                      1010
#define IDC_LIST1                       1013
#define LB_SelectedDirs                 1013
#define AddBtn                          1014
#define ctlAddBtn                       1014
#define RemoveBtn                       1015
#define ctlRemoveBtn                    1015
#define MoveUpBtn                       1016
#define ctlMUpBtn                       1016
#define MoveDownBtn                     1017
#define ctlMDownBtn                     1017
#define IDC_TREE1                       1018
#define TV_AvailDirs                    1018
#define IDC_COMBO1                      1021
#define PrntBtn                         1022
#define CreateDirBtn                    1023
#define IDC_BUTTON1                     1029
#define IDC_CHECK1                      1030
#define ctl_1                           1030
#define IDC_CHECK2                      1031
#define ctl_FF                          1031
#define IDC_CHECK3                      1032
#define ctl_x                           1032
#define IDC_CHECK4                      1033
#define ctl_S                           1033
#define IDC_CHECK5                      1034
#define ctl_D                           1034
#define IDC_CHECK6                      1035
#define ctl_m                           1035
#define IDC_CHECK7                      1036
#define ctl_f                           1036
#define IDC_CHECK8                      1037
#define ctl__w                          1037
#define IDC_CHECK9                      1038
#define ctl_q                           1038
#define IDC_CHECK10                     1039
#define ctl_T                           1039
#define IDC_CHECK11                     1040
#define ctl_4                           1040
#define IDC_EDIT1                       1041
#define ctl_I                           1041
#define IDC_CHECK13                     1042
#define ctl_L                           1042
#define IDC_CHECK14                     1043
#define ctl__l                          1043
#define IDC_CHECK15                     1044
#define ctl_G4                          1044
#define IDC_CHECK16                     1045
#define ctl_e                           1045
#define IDC_EDIT2                       1046
#define ctl_K                           1046
#define IDC_EDIT3                       1047
#define ctl_P                           1047
#define IDC_EDIT4                       1048
#define ctl_O                           1048
#define IDC_EDIT5                       1049
#define ctl_W                           1049
#define IDC_COMBO2                      1050
#define ctl_V                           1050
#define IDC_BUTTON2                     1051
#define ctl_IBrs                        1051
#define IDC_BUTTON3                     1052
#define IDC_RADIO1                      1052
#define ctl_KBrs                        1052
#define ctl_AcuBtn                      1052
#define IDC_BUTTON4                     1053
#define IDC_RADIO2                      1053
#define ctl_PBrs                        1053
#define ctl_MFBtn                       1053
#define IDC_BUTTON5                     1054
#define ctl_OBrs                        1054
#define IDC_BUTTON6                     1055
#define ctl_WBrs                        1055
#define ctl_M2                          1056
#define CCmdLine                        1057
#define ctlCCmdLine                     1057
#define ctl_X2                          1057
#define COutput                         1058
#define ctlCOutput                      1058
#define ctlTargetFile                   1059
#define ctlTargetBrs                    1060
#define ctll_FromDir                    1061
#define ctl_FromDir                     1062
#define ctl_PathToComp                  1063
#define ctl_CompBrs                     1064
#define ctl_CFlags                      1065
#define ctl_OutputDir                   1066
#define ctl_OutputDirBrs                1067
#define ctl_ObjExt                      1068
#define ctlWCmdLine                     1069
#define ctlWOutput                      1070
#define ctlDirPath                      1071
#define ctl_DirPath                     1071
#define ctl_TargetFile                  1072
#define ctl_TargetBrs                   1073
#define ctl_CLang                       1074
#define LV_Servers                      1075
#define ctll_I                          1076
#define StaticText1                     1076
#define ctll_K                          1077
#define ctll_O                          1078
#define ctll_P                          1079
#define ctll_V                          1080
#define ctll_W                          1081
#define ctll_TargetFile                 1082
#define ctll_ObjExt                     1083
#define ctlRetPath                      1083
#define ctll_OutputDir                  1084
#define ctll_PathToComp                 1085
#define ctll_CFlags                     1086
#define LV_FileList                     1120
#define CB_FileType                     1136
#define ctlCB_DirList                   1137
#define ctlFileName                     1152
#define mnu_Exit                        40001
#define mnu_ClearOutput                 40010
#define mnu_Set_Save_Dir                40016
#define mnu_Set_Save_File               40017
#define mnu_Set_Ret_Dir                 40018
#define mnu_Set_Ret_File                40019
#define mnu_Print                       40020
#define mnu_Translate                   40021
#define mnu_Compile                     40022
#define mnu_Options                     40023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40024
#define _APS_NEXT_CONTROL_VALUE         1087
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
