static char copyright[]="Copyright (c) 1988-1996 DevTech Migrations, All rights reserved.";
static char rcsid[]="$Id:$";
/*----
Fri Mar 19 23:09:38 1993
Generated by: cob2c rptwop.wcb 
Version 1.10 (c) 1991
------*/

#include "gp.h"
#include "shrthand.h"
#include "kcsifunc.h"

static char sccs_id[]="@(#)rwop.c	1.6 4/10/93";

static char error_text[81];
static char *text[]={
error_text,
"This option is used to print a report that has been previously defined.",
" ",
"           Report                         (Report Definition File)",
"           Report                         (Any date, plus edit characters)",
"           Output                         (PRINTER/DISPLAY)",
"      Change Data                         (YES or NO)",
"            Count                         (YES, NO, or 001 - 999)",
"              Sum                         (YES or NO)",
"        Lines Per                         (05 - 99)",
"           Select                         (Combination of 1 2 and 3)",
"       Print Line                         (Combination of numbers 0-5)",
/*
"              Use                         (NO = Use Internal Sort)",
*/
" ",
" ",
"        **  Press PF14 for an explanation of the Print Options  **",
"              **  Press ENTER to Continue or (16) to Exit **"
};

static void call_options_getparm();
static void val_options();


static int pf;
static screen_error_status = 0;
#define	entry_error		1
#define screen_entry_error	(screen_error_status != 0)

static char *rpt_options;

#define	rpt_id		&rpt_options[0]
#define	rpt_date	&rpt_options[8]
#define	rpt_device	&rpt_options[16]
#define	rpt_files	&rpt_options[24]
#define	rpt_option	&rpt_options[27]
#define	rpt_only	&rpt_options[30]
#define	rpt_page	&rpt_options[33]
#define	rpt_lines	&rpt_options[35]
#define	rpt_spacing	&rpt_options[38]
#define	rpt_ext_sort	&rpt_options[41]
static void main_process()
{
main_process:
	screen_error_status = 0;
	call_options_getparm();
	strcpy(error_text,"");
	if( pf == 14 )
		{
		rptphlp();
		goto main_process;
		}
	else
	if( pf == 0)
		{
		val_options();
		if( ( screen_entry_error ) )
			{
			goto main_process;
			}
		}
}
static void val_id()
{
	if( Memeq( rpt_id,"        ",8) )
		{
		screen_error_status = entry_error;
		strcpy(error_text,"Report ID is Required.");
		}
}
static void val_date()
{
}
static void val_device()
{
	if(memcmp(rpt_device,"PRINTER",7) && memcmp(rpt_device, "DISPLAY",7))
		{
		screen_error_status = entry_error;
		strcpy(error_text,"Device must be PRINTER or DISPLAY");
		}
}
static void val_files()
{
	if(memcmp(rpt_files,"YES",3) && memcmp(rpt_files,"NO ",3))
		{
		screen_error_status = entry_error;
		strcpy(error_text,"FILES must be YES or NO");
		}
}
static void val_numeric_option()
{
	int opt;

	opt = atoilen(rpt_option,3);
	if( ( opt == 0) )
		{
		screen_error_status = entry_error;
		strcpy(error_text,"OPTION must be YES or NO or 000 - 999");
		}
}
static void val_option()
{
	if(Memeq(rpt_option,"YES",3) || Memeq(rpt_option,"NO ",3))
		{
		;		/* NEXT SENTENCE */
		}
	else
		{
		val_numeric_option();
		}
}
static void val_only()
{
	if(memcmp(rpt_only,"YES",3) && memcmp(rpt_only,"NO ",3))
		{
		screen_error_status = entry_error;
		strcpy(error_text,"ONLY must be YES or NO");
		}
}
static void val_ext_sort()
{
	if(memcmp(rpt_ext_sort,"YES",3) && memcmp(rpt_ext_sort,"NO ",3))
		{
		screen_error_status = entry_error;
		strcpy(error_text,"WISPSORT must be YES or NO");
		}
}
static void val_page()
{
	int page;
	page = atoilen(rpt_page,2);
	if( ( page < 5 ) || (page > 99))
		{
		screen_error_status = entry_error;
		strcpy(error_text,"PAGE must be 05 - 99");
		}
}
static void val_lines()
{
	int idx;
	char *lines;

	for(lines = rpt_lines, idx = 0; idx < 3; ++idx)
		{
		if( (lines[idx] < '1') || (lines[idx] > '3') )
			{
			screen_error_status = entry_error;
			strcpy(error_text,"Each LINE must be 1 - 3");
			break;
			}
		}
}

static void val_spacing()
{
	int idx;
	char *spacing;

	for(spacing = rpt_spacing, idx = 0; idx < 3; ++idx)
		{
		if( (spacing[idx] < '0') || (spacing[idx] > '5') )
			{
			screen_error_status = entry_error;
			strcpy(error_text,"Each SPACING must be 0 - 5");
			break;
			}
		}
}


static void call_options_getparm()
{
	long lpf;

	wpload();
	gppfkeys=GP_PF_14|GP_PF_16;
	wswap(&gppfkeys);
	GPSETUP();
	GPSTD("OPTIONS ","REPORT");
	full_gp_text(text);
	GPKW("ID      ",rpt_id,8,12,20,"A");
	GPKW("DATE    ",rpt_date,8,13,20,"A");
	GPKW("DEVICE  ",rpt_device,7,14,20,"A");
	GPKW("FILES   ",rpt_files,3,15,20,"A");
	GPKW("OPTION  ",rpt_option,3,16,20,"A");
	GPKW("ONLY    ",rpt_only,3,17,20,"A");
	GPKW("PAGE    ",rpt_page,2,18,20,"A");
	GPKW("LINES   ",rpt_lines,3,19,20,"A");
	GPKW("SPACING ",rpt_spacing,3,20,20,"A");
/*
	GPKW("WISPSORT",rpt_ext_sort,3,21,20,"A");
*/
	GPENTER();
	GPPFS(&gppfkeys);
	lpf = display_and_read_gp();
	pf = lpf;
}
static void val_options()
{
	val_id();
	if( ( !screen_entry_error ) )
		{
		val_date();
		}
	if( ( !screen_entry_error ) )
		{
		val_device();
		}
	if( ( !screen_entry_error ) )
		{
		val_files();
		}
	if( ( !screen_entry_error ) )
		{
		val_option();
		}
	if( ( !screen_entry_error ) )
		{
		val_only();
		}
	if( ( !screen_entry_error ) )
		{
		val_page();
		}
	if( ( !screen_entry_error ) )
		{
		val_lines();
		}
	if( ( !screen_entry_error ) )
		{
		val_spacing();
		}
	if( ( !screen_entry_error ) )
		{
		val_ext_sort();
		}
}

void RPTWOP(char *RC,char *RPT_OPTIONS,char *MESSAGE)
{
	memcpy(error_text,MESSAGE,79);
	rpt_options = RPT_OPTIONS;
	memcpy(rpt_ext_sort,"NO ",3);
/*
	memcpy(rpt_ext_sort,"YES",3);
*/
	main_process();
	memcpy(RC,"000",3);
	if(pf == 16)
		memcpy(RC,"016",3);
}

/*
**	History:
**	$Log: rwop.c,v $
**	Revision 1.2  1996-09-17 19:45:51-04  gsl
**	drcs update
**
**
**
*/
