@ECHO OFF
IF EXIST VTEST.LIB DEL VTEST.LIB
CALL CC VTEST0
CALL CCLIB VTEST VTESTA ADD
CALL CCLIB VTEST VTESTB ADD
CALL CCLIB VTEST VTESTC ADD
CALL CCLIB VTEST VTESTD ADD
CALL CCLIB VTEST VTESTE ADD
CALL CCLIB VTEST VTESTF ADD
CALL CCLIB VTEST VTESTG ADD
CALL CCLIB VTEST VTESTH ADD
CALL CCLIB VTEST VTESTI ADD
CALL CCLIB VTEST VTESTJ ADD
CALL CCLIB VTEST VTESTK ADD
CALL CCLIB VTEST VTESTL ADD
CALL CCLIB VTEST VTESTM ADD
CALL CCLIB VTEST VTESTN ADD
CALL CCLIB VTEST VTESTO ADD
CALL CCLIB VTEST VTESTP ADD
CALL CCLIB VTEST VTESTQ ADD
CALL CCLIB VTEST VTESTR ADD
CALL CCLIB VTEST VTESTS ADD
CALL CCLIB VTEST VTESTT ADD
CALL CCLIB VTEST VTESTU ADD
CALL CCLIB VTEST VTESTV ADD
CALL CCLIB VTEST VTESTW ADD
CALL CCLIB VTEST VTESTX ADD
CALL CCLIB VTEST VTESTY ADD
CALL CCLIB VTEST VTESTZ ADD
LNKVTEST
