			/************************************************************************/
			/*									*/
			/*	        WISP - Wang Interchange Source Pre-processor		*/
			/*	      Copyright (c) 1988, 1989, 1990, 1991, 1992, 1993		*/
			/*	 An unpublished work of International Digital Scientific Inc.	*/
			/*			    All rights reserved.			*/
			/*									*/
			/************************************************************************/

/*
**	File:		vkeymap.h
**
**	Purpose:	To ...
**
**
**	History:
**	mm/dd/yy	Written by ...
**
*/

#ifndef vkeymap_H
#define vkeymap_H

#ifdef unix
#define VKEYMAP_FILE		"vkeymap"
#define VKEYMAP_HOME_FILE	".vkeymap"
#else
#define VKEYMAP_FILE		"VKEYMAP.DAT"
#define VKEYMAP_HOME_FILE	"VKEYMAP.DAT"
#endif

/*
**	Currently there are two types of meta keys, FUNCTION keys
**	and SPECIAL keys.  They are identified by a mask bit.
**	The function keys are generated by there value plus the mask bit.
**	The special keys are explicitly listed.
*/
#define	KM_FUNCTION_MASK	0x00010000
#define KM_SPECIAL_MASK		0x00020000

#define KM_NONE			0x00020000
#define KM_UP			0x00020001
#define KM_DOWN			0x00020002
#define KM_LEFT			0x00020003
#define KM_RIGHT		0x00020004
#define KM_ENTER		0x00020005
#define KM_PAGEUP		0x00020006
#define KM_PAGEDOWN		0x00020007
#define KM_HOME			0x00020008
#define KM_END			0x00020009
#define KM_INSERT		0x0002000a
#define KM_DELETE		0x0002000b
#define KM_BACKSPACE		0x0002000c
#define KM_UNKNOWN		0x0002ffff

char *vkeymap_path();

#endif /* vkeymap_H */
