	dcp -c -v 'scalos::scs$wisp:[ede.qahold.source]*.*' .
	dcp -c -v 'scalos::scs$wisp:[ede.qahold.include]*.*' .
	dcp -c -v 'scalos::scs$wisp:[ede.qahold.build]*.*' .
	dcp -c -v 'scalos::scs$wisp:[good.qahold.source]*.*' .
	dcp -c -v 'scalos::scs$wisp:[good.qahold.include]*.*' .
	dcp -c -v 'scalos::scs$wisp:[good.qahold.build]*.*' .
	dcp -c -v 'scalos::scs$wisp:[menudemo.qahold.source]*.*' .
	dcp -c -v 'scalos::scs$wisp:[menudemo.qahold.include]*.*' .
	dcp -c -v 'scalos::scs$wisp:[menudemo.qahold.build]*.*' .
	dcp -c -v 'scalos::scs$wisp:[common.qahold.source]*.*' .
	dcp -c -v 'scalos::scs$wisp:[common.qahold.include]*.*' .
