@ECHO OFF
SET COMSPEC=C:\DOS\COMMAND.COM
VERIFY OFF
PATH .;E:\WISPBIN;E:\DLOCAL;E:\DBIN;C:\DOS;C:\PCTCP
SET LIB=E:\LIB;E:\C600\LIB;E:\COBOL\LIB;E:\COBOL\LBR;E:\COBOL\LBR\LIB
SET INCLUDE=E:\INCLUDE
SET HELPFILES=E:\LANGS\HELP\*.HLP
SET INIT=E:\INIT
SET COBDIR=E:\COBOL\LBR;E:\COBOL\EXEDLL;
SET COBHNF=E:\COBOL\ON-LINE;
SET CWWORK=E:\COBOL\DEMO\COWRITER
SET CWFILES=E:\COBOL\DEMO\COWRITER
SET CWRSYSTEM=E:\COBOL\LBR
SET ASMEX=E:\MASM\SAMPLES
SET XVIPATH=E:\WORK\UTILS
C:\DOS\APPEND /E
C:\DOS\APPEND C:\DOS
LOADHIGH C:\DOS\FASTOPEN C:=100 E:=200 F:
LOADHIGH DOSKEY
LOADHIGH \PCTCP\wd8003e 0x62 2 0x280 0xd800
LOADHIGH \PCTCP\ethdrv
LOADHIGH c:\mouse\mouse
LOADHIGH C:\MOUSE\CLICK
PROMPT $P$G
VER
DOSSHELL /G:M
