# Makefile to create new version of "runcbl" or "acuconnect" based on
# changes to "sub.c"
# To relink the runtime type: make runcbl
# To relink the AcuConnect server type: make acuconnect
# Distributed with ACUCOBOL-GT version 4.0.0
# PMK: alpha

CC = cc
X11_INCLUDE_FLAGS =
CFLAGS = -O $(X11_INCLUDE_FLAGS) $(ACUSERVER_FLAGS)
LDFLAGS = -s

# If your ACUCOBOL libraries are in another directory, change the value
# of ACU_LIBDIR to point at them.
ACU_LIBDIR = .

# Use the following two lines for an AcuServer-DISABLED runtime
#ACUSERVER_FLAGS = -DNO_CLIENT=1
#ACUSERVER_LIBS = # nothing - no networking libraries are necessary

# Use the following two lines for an AcuServer-ENABLED runtime
ACUSERVER_FLAGS =
ACUSERVER_LIBS = $(ACU_LIBDIR)/libclnt.a

CONNECT_C = $(ACU_LIBDIR)/libconnectc.a
CONNECT_S = $(ACU_LIBDIR)/libconnects.a

# File System Interface section.
# These subs/libs are for any extra file systems you want to link in.
FSI_SUBS =
FSI_LIBS =

LIBS =  $(ACU_LIBDIR)/libruncbl.a \
	$(ACU_LIBDIR)/libfsi.a \
	$(ACU_LIBDIR)/libacuterm.a \
	$(ACU_LIBDIR)/libvision.a \
	$(ACUSERVER_LIBS) \
	$(FSI_LIBS) \
	$(ACU_LIBDIR)/liblib.a \
	$(ACU_LIBDIR)/libmessage.a \
	$(ACU_LIBDIR)/libmemory.a \
	$(ACU_LIBDIR)/libstdlib.a \
	-lm

SUBS = sub.o filetbl.o $(FSI_SUBS)

runcbl: $(SUBS)
	$(CC) $(LDFLAGS) -o runcbl $(SUBS) $(LIBS) $(CONNECT_C)

acuconnect: $(SUBS)
	$(CC) $(LDFLAGS) -o acuconnect $(SUBS) $(ACU_LIBDIR)/libruncbl.a \
			$(CONNECT_S) $(LIBS)

sub.o: sub.c sub85.c config85.c direct.c

clean:
	-rm -f runcbl sub.o filetbl.o
