#!/bin/sh
#
#	Usage: cpioz {source directory}
#
MYNAME=cpioz
SRCDIR=$1
OUTFILE=$SRCDIR.cpio.Z

if [ "$SRCDIR" = "" ]
then
	echo "Usage: $MYNAME {source directory}"
	exit 1
fi

if [ ! -d $SRCDIR ]
then
	echo "Error: $SRCDIR is not a directory"
	exit 1
fi

find $SRCDIR -print|cpio -ocv|compress>$OUTFILE
RC=$?

if [ $RC != 0 ]
then
	echo "$MYNAME failed with RC=$RC"
	exit 1
fi

echo Created $OUTFILE

ls -l $OUTFILE
exit 0

