#!/bin/sh
#
#	Usage: uncpioz {source}.cpio.Z
#
MYNAME=uncpioz
ARG1=$1

if [ "$ARG1" = "" ]
then
	echo "Usage: $MYNAME {source}.cpio.Z"
	exit 1
fi

# Strip off then re-add the .cpio.Z
SOURCE=`echo $1|sed 's/\.cpio\.Z//'`
SOURCE=$SOURCE.cpio.Z

if [ ! -f $SOURCE ]
then
	echo "Error: $SOURCE is not a file"
	exit 1
fi

uncompress -c $SOURCE|cpio -icvd
RC=$?

if [ $RC != 0 ]
then
	echo "$MYNAME failed with RC=$RC"
	exit 1
fi

exit 0
