#!/bin/sh
#
#	Usage: untarz {source}.tar.Z
#
MYNAME=untarz
ARG1=$1

if [ "$ARG1" = "" ]
then
	echo "Usage: $MYNAME {source}.tar.Z"
	exit 1
fi

# Strip off then re-add the .tar.Z
SOURCE=`echo $1|sed 's/\.tar\.Z//'`
SOURCE=$SOURCE.tar.Z

if [ ! -f $SOURCE ]
then
	echo "Error: $SOURCE is not a file"
	exit 1
fi

uncompress -c $SOURCE|tar -xvpf -
RC=$?

if [ $RC != 0 ]
then
	echo "$MYNAME failed with RC=$RC"
	exit 1
fi

exit 0

