#!/bin/sh -
#
# Usage: wmkdep *.c
#
# Copyright (c) 1987 Regents of the University of California.
# All rights reserved.
#
# Redistribution and use in source and binary forms are permitted
# provided that the above copyright notice and this paragraph are
# duplicated in all such forms and that any documentation,
# advertising materials, and other materials related to such
# distribution and use acknowledge that the software was developed
# by the University of California, Berkeley.  The name of the
# University may not be used to endorse or promote products derived
# from this software without specific prior written permission.
# THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
# WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR A PARTICULAR PURPOSE.
#
#	@(#)mkdep.sh	5.17 (Berkeley) 10/24/88
#
PATH=/bin:/usr/bin:/usr/ucb
export PATH

D=.depend			# default dependency file is .depend
append=0

while :
	do case "$1" in
		# -a appends to the depend file
		-a)
			append=1
			shift ;;

		# -f allows you to select a makefile name
		-f)
			D=$2
			shift; shift ;;

		# the -p flag produces "program: program.c" style dependencies
		# so .o's don't get produced
		-p)
			SED='s;\.o;;'
			shift ;;
		*)
			break ;;
	esac
done

if [ $# = 0 ] ; then
#	echo 'usage: mkdep [-p] [-f depend_file] [cc_flags] file ...'
	echo 'usage: mkdep [-f depend_file] *.c'
	exit 1
fi

TMP=/tmp/mkdep$$

trap 'rm -f $TMP ; exit 1' 1 2 3 13 15

MYCFLAGS="-I ../wispcommon -I ../videolib -DAIX -Dunix  -qlanglvl=ansi"

rm -f *.u

#
#  CC creates *.u files that look like this:
#
#	vwang.o: vwang.c
#	vwang.o: /usr/include/stdio.h
#	vwang.o: /usr/include/sys/wait.h
#	vwang.o: ../videolib/video.h
#	vwang.o: ../videolib/vlocal.h
#	vwang.o: ../wispcommon/setenvst.h
#	vwang.o: ../wispcommon/wexit.h
#	vwang.o: assert.h
#	vwang.o: wsfns.h
#
#  Sed then to:
#	- Remove system "/usr/include" lines
#	- Change "../videolib" to "$(VC)"
#	- Change "../wispcommon" to "$(WC)"
#	- Make the objects part of a lib "$(THE_LIB)(xxx.o)"
#
#  Result looks like:
#
#	$(THE_LIB)(vwang.o): vwang.c
#	$(THE_LIB)(vwang.o): $(VC)/video.h
#	$(THE_LIB)(vwang.o): $(VC)/vlocal.h
#	$(THE_LIB)(vwang.o): $(WC)/setenvst.h
#	$(THE_LIB)(vwang.o): $(WC)/wexit.h
#	$(THE_LIB)(vwang.o): assert.h
#	$(THE_LIB)(vwang.o): wsfns.h
#

cc $MYCFLAGS -ME $* >/dev/null; cat *.u |
sed "
	s; \./; ;g
	/\.c:$/d
	s;\.\./videolib/;\$(VC)/;g
	s;\.\./wispcommon/;\$(WC)/;g
	/\/usr\/include\//d
	s;^;\$(THE_LIB)(;
	s;\.o:;.o):;
	$SED" > $TMP

if [ $append = 1 ]; then
	cat $TMP >> $D
	rm -f $TMP
else
	mv $TMP $D
fi
exit 0
