# Makefile to create new version of "runcbl" or "acuconnect" based on
# changes to "sub.c"
# To relink the runtime type: make runcbl
# To relink the AcuConnect server type: make acuconnect
# Distributed with ACUCOBOL-GT version 4.2.0
# PMK: 00061084A100

#CC = cc -qarch=com      # AIX 4.3
#CC = cc -Ae +DAportable # HP-UX 10.20
CC = cc
CFLAGS = -O $(ACUSERVER_FLAGS) $(ACUCONNECT_FLAGS)
LDFLAGS = -s

# If your ACUCOBOL libraries are in another directory, change the value
# of ACU_LIBDIR to point at them.
ACU_LIBDIR = .

#
# AcuServer configuration
#

# Use the following two lines for an AcuServer-DISABLED runtime
#ACUSERVER_FLAGS = -DNO_CLIENT=1
#ACUSERVER_LIBS = # nothing - no networking libraries are necessary

# Use the following two lines for an AcuServer-ENABLED runtime
ACUSERVER_FLAGS =
ACUSERVER_LIBS = $(ACU_LIBDIR)/libclnt.a

#
# AcuConnect configuration
#

# Use the following three lines for an AcuConnect-DISABLED runtime
#ACUCONNECT_FLAGS = -DNO_ACUCONNECT=1
#CONNECT_C =
#CONNECT_S =

# Use the following three lines for an AcuConnect-ENABLED runtime
ACUCONNECT_FLAGS =
CONNECT_C = $(ACU_LIBDIR)/libconnectc.a
CONNECT_S = $(ACU_LIBDIR)/libconnects.a

#
# File System Infterface configuration
#

# These subs/libs are for any extra file systems you want to link in.
FSI_SUBS =
FSI_LIBS =


RUNLIB = $(ACU_LIBDIR)/libruncbl.a

LIBS =  $(ACUSERVER_LIBS) \
	$(ACU_LIBDIR)/libfsi.a \
	$(ACU_LIBDIR)/libacuterm.a \
	$(ACU_LIBDIR)/libvision.a \
	$(FSI_LIBS) \
	$(ACU_LIBDIR)/liblib.a \
	$(ACU_LIBDIR)/libmessage.a \
	$(ACU_LIBDIR)/libmemory.a \
	$(ACU_LIBDIR)/libstdlib.a \
	-lm

SUBS = sub.o filetbl.o $(FSI_SUBS)

runcbl: $(SUBS)
	$(CC) $(LDFLAGS) -o runcbl $(SUBS) $(RUNLIB) $(CONNECT_C) $(LIBS) 

acuconnect: $(SUBS)
	$(CC) $(LDFLAGS) -o acuconnect $(SUBS) $(RUNLIB) $(CONNECT_S) $(LIBS)

sub.o: sub.c sub85.c config85.c direct.c Makefile

clean:
	-rm -f runcbl acuconnect sub.o filetbl.o
